# spring.application.name=user_service
# spring.rsocket.server.port=7001
# spring.rsocket.server.ssl.enabled=true
# spring.rsocket.server.ssl.client-auth=need
# spring.rsocket.server.ssl.key-store=${USER_KEYSTORE_PATH}
# spring.rsocket.server.ssl.key-store-type=PKCS12
# spring.rsocket.server.ssl.key-store-password=${USER_KEYSTORE_PASSWORD}
# spring.rsocket.server.ssl.trust-store=${TRUSTSTORE_PATH}
# spring.rsocket.server.ssl.trust-store-type=PKCS12
# spring.rsocket.server.ssl.trust-store-password=${TRUSTSTORE_PASSWORD}
# spring.main.web-application-type=none

# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.r2dbc.user.url=jdbc:postgresql://localhost:5432/user
# spring.r2dbc.user.username=${DB_USERNAME}
# spring.r2dbc.user.password=${DB_PASSWORD}

# spring.r2dbc.location.url=r2dbc:postgresql://localhost:5432/location
# spring.r2dbc.location.username=${DB_USERNAME}
# spring.r2dbc.location.password=${DB_PASSWORD}

# jwt.service.public=${JWT_SERVICE_PUBLIC_KEY}